name: Create Linear Issue

on:
  issues:
    types: [opened]

jobs:
  create-linear-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Linear Issue
        uses: Dev-CasperTheGhost/create-linear-issue@1.3.1
        with:
          # from GitHub Secrets within the repo
          linear-api-token: ${{ secrets.LINEAR_API_TOKEN }}
          team-id: ${{ secrets.LINEAR_TEAM_ID }}
          state-id: ${{ secrets.LINEAR_STATE_ID }}
