name: Create new issues to Linear

on:
  issues:
    types: [opened]

jobs:
  create-linear-issue:
    runs-on: ubuntu-latest
    steps:
      - name: 'Create issue in Linear'
        uses: seripap/gh-linear-action@v1.0.4
        with:
          linear-key: ${{ secrets.LINEAR_API_TOKEN }}
          linear-team-id: ${{ secrets.LINEAR_TEAM_ID }}
          title: ${{ github.event.issue.title }}
          body: ${{ github.event.issue.body }}
          url: ${{ github.event.issue.html_url }}
